name: helm-chart-release

on:
  push:
    branches: ["feat/helm-release"]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        chart:
          - edc-kafka-demo
          - tractusx-edc-kafka

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ensure gh-pages branch exists (no checkout)
        shell: bash
        run: |
          set -euo pipefail
          if ! git ls-remote --exit-code --heads origin gh-pages; then
            EMPTY_TREE="$(git hash-object -t tree /dev/null)"
            COMMIT="$(printf "Initialize gh-pages branch\n" | git commit-tree "$EMPTY_TREE")"
            git update-ref refs/heads/gh-pages "$COMMIT"
            git push origin refs/heads/gh-pages
          fi

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Configure Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add eclipse-tractusx https://eclipse-tractusx.github.io/charts/dev
          helm repo update

      - name: Build dependencies (${{ matrix.chart }})
        run: |
          helm dependency build charts/${{ matrix.chart }} || true

      - name: Run chart-releaser (${{ matrix.chart }})
        id: cr
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          charts_dir: charts/${{ matrix.chart }}
          config: ./.github/configs/cr-config.yml
