name: helm-chart-release

on:
  push:
    branches:
      - "feat/helm-release"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Configure Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add eclipse-tractusx https://eclipse-tractusx.github.io/charts/dev
          helm repo update

      - name: Build chart dependencies (only the two allowed charts)
        run: |
          helm dependency build charts/edc-kafka-demo || true
          helm dependency build charts/tractusx-edc-kafka || true

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          charts_dir: charts
          packages_with_index: true
          skip_existing: true
          config: cr.yaml
