name: helm-chart-release

on:
  push:
    branches: ["feat/helm-release"]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ensure gh-pages branch exists
        run: |
          if ! git ls-remote --exit-code --heads origin gh-pages; then
            git switch --orphan gh-pages
            git reset --hard
            echo "# Helm chart repo" > README.md
            git add README.md
            git commit -m "Initialize gh-pages branch"
            git push origin gh-pages
            git switch -
          fi

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Configure Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add eclipse-tractusx https://eclipse-tractusx.github.io/charts/dev
          helm repo update

      - name: Build chart dependencies
        run: |
          helm dependency build charts/edc-kafka-demo || true
          helm dependency build charts/tractusx-edc-kafka || true

      - name: Package only allowed charts
        run: |
          mkdir -p .cr-release-packages
          helm package charts/edc-kafka-demo --destination .cr-release-packages
          helm package charts/tractusx-edc-kafka --destination .cr-release-packages

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          charts_dir: charts
          packages_with_index: true
          skip_existing: true
          skip_packaging: true
